 #getting correct python
FROM python:3.12-slim
# setting working directory
WORKDIR /app
#copying program
COPY memory_tracker.py .
#dependencies to download
RUN pip install psutil
#run command
CMD ["python3" , "memory_tracker.py"]

